// Banco de mensagens dinâmicas do Radar — por categoria e gênero.
// Placeholders: {nome} {n} {missao} {pct} {dias} — substituídos em tempo de execução.
// m = masculino, f = feminino. Aluno sem gênero cadastrado não gera evento no Radar.
//
// Categorias de inatividade em 3 níveis (tom mais leve -> mais forte):
//   inatividade_leve_5d    -> dispara com 5+ dias sem check-in
//   inatividade_media_15d  -> dispara com 15+ dias sem check-in
//   inatividade_grave_30d  -> dispara com 30+ dias sem check-in
export const RADAR_MSGS = {
  inatividade_leve_5d: [
    { m: "{nome} sumiu há {dias} dias. Nada grave, só sentimos falta.", f: "{nome} sumiu há {dias} dias. Nada grave, só sentimos falta." },
    { m: "{dias} dias sem {nome} por aqui. A bike dele tá com saudade.", f: "{dias} dias sem {nome} por aqui. A bike dela tá com saudade." },
    { m: "Ei, {nome}, {dias} dias já! Tá tudo bem por aí?", f: "Ei, {nome}, {dias} dias já! Tá tudo bem por aí?" },
    { m: "{nome} deu uma pausa — {dias} dias. A gente guarda o lugar.", f: "{nome} deu uma pausa — {dias} dias. A gente guarda o lugar." },
    { m: "Faz {dias} dias que não vemos {nome}. Semana corrida, deve ser.", f: "Faz {dias} dias que não vemos {nome}. Semana corrida, deve ser." },
    { m: "{dias} dias parado. {nome}, a sala continua te esperando.", f: "{dias} dias parada. {nome}, a sala continua te esperando." },
    { m: "Alguém viu {nome}? Já são {dias} dias sem aparecer.", f: "Alguém viu {nome}? Já são {dias} dias sem aparecer." },
    { m: "{nome} some por umas semaninhas de vez em quando — {dias} dias dessa vez.", f: "{nome} some por umas semaninhas de vez em quando — {dias} dias dessa vez." },
    { m: "{dias} dias sem check-in de {nome}. Deve tá numa fase corrida.", f: "{dias} dias sem check-in de {nome}. Deve tá numa fase corrida." },
    { m: "Oi, {nome}! Notamos os {dias} dias de ausência. Bora voltar quando der.", f: "Oi, {nome}! Notamos os {dias} dias de ausência. Bora voltar quando der." },
    { m: "{nome} tirou {dias} dias de folga. Merecido, mas sentimos falta.", f: "{nome} tirou {dias} dias de folga. Merecido, mas sentimos falta." },
    { m: "{dias} dias sem ver {nome} na sala. Nada como uma pedalada pra recomeçar.", f: "{dias} dias sem ver {nome} na sala. Nada como uma pedalada pra recomeçar." },
    { m: "A cartela de {nome} tá esperando — {dias} dias parada.", f: "A cartela de {nome} tá esperando — {dias} dias parada." },
    { m: "{nome}, {dias} dias sem te ver por aqui. Vem quando puder.", f: "{nome}, {dias} dias sem te ver por aqui. Vem quando puder." },
    { m: "Sentimos a falta de {nome} — {dias} dias e contando.", f: "Sentimos a falta de {nome} — {dias} dias e contando." },
    { m: "{dias} dias de pausa pra {nome}. A gente entende, mas torce pela volta.", f: "{dias} dias de pausa pra {nome}. A gente entende, mas torce pela volta." },
    { m: "{nome} desapareceu discretamente — {dias} dias já.", f: "{nome} desapareceu discretamente — {dias} dias já." },
    { m: "Um lembrete gentil: {nome} tá há {dias} dias sem check-in.", f: "Um lembrete gentil: {nome} tá há {dias} dias sem check-in." },
    { m: "{dias} dias sem pedal. {nome}, a próxima aula te espera.", f: "{dias} dias sem pedal. {nome}, a próxima aula te espera." },
    { m: "Notamos: {nome} sumiu há {dias} dias. Bike parada, mas a vaga é sua.", f: "Notamos: {nome} sumiu há {dias} dias. Bike parada, mas a vaga é sua." },
    { m: "{nome}, já são {dias} dias. Sem pressão, só um alô.", f: "{nome}, já são {dias} dias. Sem pressão, só um alô." },
    { m: "Passou uma semaninha sem {nome} — {dias} dias. Tudo certo por aí?", f: "Passou uma semaninha sem {nome} — {dias} dias. Tudo certo por aí?" },
    { m: "{dias} dias e a bike de {nome} ainda tá esperando o dono voltar.", f: "{dias} dias e a bike de {nome} ainda tá esperando a dona voltar." },
  ],
  inatividade_media_15d: [
    { m: "{nome} já tá há {dias} dias sem check-in. Bora mandar um oi pra trazer ele de volta?", f: "{nome} já tá há {dias} dias sem check-in. Bora mandar um oi pra trazer ela de volta?" },
    { m: "{dias} dias sem {nome}. Comunidade, essa é a hora de puxar de volta.", f: "{dias} dias sem {nome}. Comunidade, essa é a hora de puxar de volta." },
    { m: "Já faz {dias} dias. {nome}, a sala não é a mesma sem você.", f: "Já faz {dias} dias. {nome}, a sala não é a mesma sem você." },
    { m: "{nome} sumiu de verdade — {dias} dias já. Quem tem contato, chama.", f: "{nome} sumiu de verdade — {dias} dias já. Quem tem contato, chama." },
    { m: "{dias} dias parado é tempo demais. Vamos resgatar {nome}?", f: "{dias} dias parada é tempo demais. Vamos resgatar {nome}?" },
    { m: "Alerta amarelo: {nome} tá há {dias} dias fora. Bora fazer barulho pra ele voltar.", f: "Alerta amarelo: {nome} tá há {dias} dias fora. Bora fazer barulho pra ela voltar." },
    { m: "{nome} não é de sumir assim — {dias} dias já é bastante. Alguém chama.", f: "{nome} não é de sumir assim — {dias} dias já é bastante. Alguém chama." },
    { m: "{dias} dias sem {nome}. A comunidade sente falta de verdade.", f: "{dias} dias sem {nome}. A comunidade sente falta de verdade." },
    { m: "Já é caso pra intervenção amigável: {nome}, {dias} dias sumido, precisamos de você de volta.", f: "Já é caso pra intervenção amigável: {nome}, {dias} dias sumida, precisamos de você de volta." },
    { m: "{nome} tá devendo aula há {dias} dias. Quem chama esse cara de volta?", f: "{nome} tá devendo aula há {dias} dias. Quem chama essa mulher de volta?" },
    { m: "{dias} dias é tempo de sentir falta e agir. Manda mensagem pra {nome}.", f: "{dias} dias é tempo de sentir falta e agir. Manda mensagem pra {nome}." },
    { m: "A ausência de {nome} já dura {dias} dias. Bora trazer de volta com carinho.", f: "A ausência de {nome} já dura {dias} dias. Bora trazer de volta com carinho." },
    { m: "{nome}, {dias} dias é muita coisa. A gente tá aqui, sempre que quiser voltar.", f: "{nome}, {dias} dias é muita coisa. A gente tá aqui, sempre que quiser voltar." },
    { m: "{dias} dias sem check-in pesa. Comunidade, hora de mostrar que sentimos falta de {nome}.", f: "{dias} dias sem check-in pesa. Comunidade, hora de mostrar que sentimos falta de {nome}." },
    { m: "Chegou aos {dias} dias — {nome} precisa de um empurrão da galera.", f: "Chegou aos {dias} dias — {nome} precisa de um empurrão da galera." },
    { m: "{nome} some por {dias} dias e ninguém aqui esquece dele. Vamos chamar de volta.", f: "{nome} some por {dias} dias e ninguém aqui esquece dela. Vamos chamar de volta." },
    { m: "{dias} dias parado pesa na cartela e no coração da comunidade. Bora, {nome}?", f: "{dias} dias parada pesa na cartela e no coração da comunidade. Bora, {nome}?" },
    { m: "Já passou da conta: {dias} dias sem {nome}. Hora de mandar aquele incentivo.", f: "Já passou da conta: {dias} dias sem {nome}. Hora de mandar aquele incentivo." },
    { m: "{nome}, {dias} dias longe da bike. A gente guardou seu lugar — volta.", f: "{nome}, {dias} dias longe da bike. A gente guardou seu lugar — volta." },
    { m: "Time de resgate ativado: {nome} tá há {dias} dias sumido.", f: "Time de resgate ativado: {nome} tá há {dias} dias sumida." },
    { m: "{dias} dias é sinal de alerta. Comunidade, chama {nome} de volta com carinho.", f: "{dias} dias é sinal de alerta. Comunidade, chama {nome} de volta com carinho." },
    { m: "{nome} desapareceu por {dias} dias — bora fazer ele sentir a falta que faz aqui.", f: "{nome} desapareceu por {dias} dias — bora fazer ela sentir a falta que faz aqui." },
    { m: "Não deixa {nome} desistir — já são {dias} dias, hora de mostrar apoio.", f: "Não deixa {nome} desistir — já são {dias} dias, hora de mostrar apoio." },
  ],
  inatividade_grave_30d: [
    { m: "{nome} tá há {dias} dias sem aparecer. Comunidade, precisamos trazer ele de volta — manda mensagem agora.", f: "{nome} tá há {dias} dias sem aparecer. Comunidade, precisamos trazer ela de volta — manda mensagem agora." },
    { m: "{dias} dias é tempo demais. {nome}, sua vaga na Spincycle continua guardada — volta pra gente.", f: "{dias} dias é tempo demais. {nome}, sua vaga na Spincycle continua guardada — volta pra gente." },
    { m: "Alerta vermelho: {nome} sumiu há {dias} dias. Quem puder, chama ele hoje mesmo.", f: "Alerta vermelho: {nome} sumiu há {dias} dias. Quem puder, chama ela hoje mesmo." },
    { m: "Um mês sem {nome} ({dias} dias). A gente não desiste de ninguém — bora buscar de volta.", f: "Um mês sem {nome} ({dias} dias). A gente não desiste de ninguém — bora buscar de volta." },
    { m: "{nome}, sentimos sua falta de verdade — {dias} dias sem você aqui. Volta quando puder, sem cobrança.", f: "{nome}, sentimos sua falta de verdade — {dias} dias sem você aqui. Volta quando puder, sem cobrança." },
    { m: "{dias} dias de ausência é hora de agir. Comunidade, manda um carinho pra {nome}.", f: "{dias} dias de ausência é hora de agir. Comunidade, manda um carinho pra {nome}." },
    { m: "A gente não esquece de ninguém: {nome} tá há {dias} dias fora, e a porta continua aberta.", f: "A gente não esquece de ninguém: {nome} tá há {dias} dias fora, e a porta continua aberta." },
    { m: "{nome} completou {dias} dias longe. Se alguém tiver contato, um oi faz toda diferença agora.", f: "{nome} completou {dias} dias longe. Se alguém tiver contato, um oi faz toda diferença agora." },
    { m: "{dias} dias sem check-in é sinal grande. {nome}, a Spincycle sente sua falta.", f: "{dias} dias sem check-in é sinal grande. {nome}, a Spincycle sente sua falta." },
    { m: "Já é hora de mobilizar: {nome} sumiu há {dias} dias. Vamos resgatar juntos.", f: "Já é hora de mobilizar: {nome} sumiu há {dias} dias. Vamos resgatar juntos." },
    { m: "{nome}, {dias} dias é muito tempo pra ficar de fora. Sua bike, seu lugar, continuam esperando.", f: "{nome}, {dias} dias é muito tempo pra ficar de fora. Sua bike, seu lugar, continuam esperando." },
    { m: "Comunidade, precisamos falar sobre {nome}: {dias} dias sem aparecer. Bora trazer de volta.", f: "Comunidade, precisamos falar sobre {nome}: {dias} dias sem aparecer. Bora trazer de volta." },
    { m: "{dias} dias de silêncio. {nome}, se estiver vendo isso: sua turma sente sua falta.", f: "{dias} dias de silêncio. {nome}, se estiver vendo isso: sua turma sente sua falta." },
    { m: "Já se vão {dias} dias sem {nome}. Ninguém fica de fora — bora chamar de volta com carinho.", f: "Já se vão {dias} dias sem {nome}. Ninguém fica de fora — bora chamar de volta com carinho." },
    { m: "{nome} tá longe há {dias} dias. Se algo aconteceu, a gente tá aqui — sem cobrança, só apoio.", f: "{nome} tá longe há {dias} dias. Se algo aconteceu, a gente tá aqui — sem cobrança, só apoio." },
    { m: "{dias} dias sem {nome} pesa pra comunidade inteira. Bora fazer a diferença hoje.", f: "{dias} dias sem {nome} pesa pra comunidade inteira. Bora fazer a diferença hoje." },
    { m: "Chegamos aos {dias} dias, {nome}. Independente do motivo, aqui sempre tem lugar pra você.", f: "Chegamos aos {dias} dias, {nome}. Independente do motivo, aqui sempre tem lugar pra você." },
    { m: "{nome} sumiu há {dias} dias — comunidade, essa é a hora de mostrar que ninguém pedala sozinho.", f: "{nome} sumiu há {dias} dias — comunidade, essa é a hora de mostrar que ninguém pedala sozinho." },
    { m: "{dias} dias é tempo de reconectar. {nome}, sua cartela e sua turma seguem te esperando.", f: "{dias} dias é tempo de reconectar. {nome}, sua cartela e sua turma seguem te esperando." },
    { m: "A ausência de {nome} já passou de {dias} dias. Comunidade, vamos juntos trazer de volta.", f: "A ausência de {nome} já passou de {dias} dias. Comunidade, vamos juntos trazer de volta." },
    { m: "{nome}, {dias} dias longe é bastante — mas a volta pode ser a qualquer momento, sem culpa.", f: "{nome}, {dias} dias longe é bastante — mas a volta pode ser a qualquer momento, sem culpa." },
    { m: "Time Spincycle não desiste: {nome} tá há {dias} dias fora, e a torcida continua.", f: "Time Spincycle não desiste: {nome} tá há {dias} dias fora, e a torcida continua." },
    { m: "{dias} dias sem notícia de {nome}. Um recado carinhoso pode ser o empurrão que falta.", f: "{dias} dias sem notícia de {nome}. Um recado carinhoso pode ser o empurrão que falta." },
  ],
  madrugada: [
    { m: "{nome} madrugou pela {n}ª vez. Tá merecendo um cafézinho.", f: "{nome} madrugou pela {n}ª vez. Tá merecendo um cafézinho." },
    { m: "O despertador de {nome} não perdoa: {n}ª madrugada e lá estava ele às 5h50.", f: "O despertador de {nome} não perdoa: {n}ª madrugada e lá estava ela às 5h50." },
    { m: "{n}ª vez que {nome} encara o sol nascendo pedalando. Respeito.", f: "{n}ª vez que {nome} encara o sol nascendo pedalando. Respeito." },
    { m: "Enquanto a cidade dorme, {nome} já tá na {n}ª madrugada de pedal.", f: "Enquanto a cidade dorme, {nome} já tá na {n}ª madrugada de pedal." },
    { m: "{nome} de novo às 5h50 — {n}ª vez. Esse cara não brinca.", f: "{nome} de novo às 5h50 — {n}ª vez. Essa mulher não brinca." },
    { m: "Café reforçado pra {nome}, que já são {n} madrugadas nessa reta.", f: "Café reforçado pra {nome}, que já são {n} madrugadas nessa reta." },
    { m: "{n}ª madrugada de {nome}. O galo ainda nem cantou e ele já tava pedalando.", f: "{n}ª madrugada de {nome}. O galo ainda nem cantou e ela já tava pedalando." },
    { m: "Quem chega antes do sol nascer merece aplauso: {nome}, {n}ª vez.", f: "Quem chega antes do sol nascer merece aplauso: {nome}, {n}ª vez." },
    { m: "{nome} tá coleciando madrugada — já são {n}. O travesseiro que se cuide.", f: "{nome} tá coleciando madrugada — já são {n}. O travesseiro que se cuide." },
    { m: "5h50 de novo e {nome} lá, firme. {n}ª vez já.", f: "5h50 de novo e {nome} lá, firme. {n}ª vez já." },
    { m: "O título de madrugador tá ficando difícil de tirar de {nome} — {n}ª vez.", f: "O título de madrugadora tá ficando difícil de tirar de {nome} — {n}ª vez." },
    { m: "{n} madrugadas e {nome} nunca chegou atrasado. Isso é disciplina.", f: "{n} madrugadas e {nome} nunca chegou atrasada. Isso é disciplina." },
    { m: "Quando o despertador toca 5h30, {nome} já sabe: hora do pedal. {n}ª vez.", f: "Quando o despertador toca 5h30, {nome} já sabe: hora do pedal. {n}ª vez." },
    { m: "{nome} e a madrugada já são íntimos — {n}ª vez esse ano.", f: "{nome} e a madrugada já são íntimas — {n}ª vez esse ano." },
    { m: "Bateu recorde pessoal de disposição: {nome} na {n}ª madrugada.", f: "Bateu recorde pessoal de disposição: {nome} na {n}ª madrugada." },
    { m: "Ninguém acredita que {nome} acorda tão cedo, mas são {n} provas.", f: "Ninguém acredita que {nome} acorda tão cedo, mas são {n} provas." },
    { m: "{n}ª madrugada de {nome} — o sono perdeu essa disputa de novo.", f: "{n}ª madrugada de {nome} — o sono perdeu essa disputa de novo." },
    { m: "Cafézinho pra {nome} que já tá na conta de {n} madrugadas.", f: "Cafézinho pra {nome} que já tá na conta de {n} madrugadas." },
    { m: "{nome} prova de novo: {n}ª madrugada, zero desculpa.", f: "{nome} prova de novo: {n}ª madrugada, zero desculpa." },
  ],
  aula_dobrada: [
    { m: "Hoje {nome} fez 2 aulas seguidas... acho que precisa de um shake bem gelado. Quem dá um pra ele?", f: "Hoje {nome} fez 2 aulas seguidas... acho que precisa de um shake bem gelado. Quem dá um pra ela?" },
    { m: "{nome} dobrou a aula hoje. Aquele suor extra tem nome: dedicação.", f: "{nome} dobrou a aula hoje. Aquele suor extra tem nome: dedicação." },
    { m: "Duas aulas no mesmo dia pra {nome}. Alguém segura essa energia.", f: "Duas aulas no mesmo dia pra {nome}. Alguém segura essa energia." },
    { m: "{nome} achou pouco uma aula e foi na segunda também. Respeito.", f: "{nome} achou pouco uma aula e foi na segunda também. Respeito." },
    { m: "Bike dupla hoje: {nome} não parou na primeira. Fôlego de sobra.", f: "Bike dupla hoje: {nome} não parou na primeira. Fôlego de sobra." },
    { m: "{nome} fez a manhã e a noite hoje. Amanhã as pernas vão cobrar, mas valeu.", f: "{nome} fez a manhã e a noite hoje. Amanhã as pernas vão cobrar, mas valeu." },
    { m: "Quem viu {nome} entrar de novo na sala depois da primeira aula sabe: foi sério hoje.", f: "Quem viu {nome} entrar de novo na sala depois da primeira aula sabe: foi sério hoje." },
    { m: "{nome} decidiu que uma aula não bastava. Duas hoje, sem reclamar.", f: "{nome} decidiu que uma aula não bastava. Duas hoje, sem reclamar." },
    { m: "Aula dobrada é nível avançado, e {nome} passou no teste hoje.", f: "Aula dobrada é nível avançado, e {nome} passou no teste hoje." },
    { m: "{nome} suou o dobro hoje — 2 aulas, 1 dia só. Bike merece um descanso.", f: "{nome} suou o dobro hoje — 2 aulas, 1 dia só. Bike merece um descanso." },
    { m: "Quando 1 aula não é suficiente: o caso de {nome} hoje.", f: "Quando 1 aula não é suficiente: o caso de {nome} hoje." },
    { m: "{nome} topou o desafio extra hoje — segunda aula do dia, sem desculpa.", f: "{nome} topou o desafio extra hoje — segunda aula do dia, sem desculpa." },
    { m: "Hoje tem gente que exagerou (no bom sentido): {nome} fez dose dupla.", f: "Hoje tem gente que exagerou (no bom sentido): {nome} fez dose dupla." },
    { m: "{nome} provou hoje que cansaço é questão de ponto de vista — 2 aulas no mesmo dia.", f: "{nome} provou hoje que cansaço é questão de ponto de vista — 2 aulas no mesmo dia." },
    { m: "Duas vezes na bike hoje pra {nome}. A vontade de ganhar fala mais alto.", f: "Duas vezes na bike hoje pra {nome}. A vontade de ganhar fala mais alto." },
    { m: "{nome} fechou o dia com 2 aulas. Alguém chama a massagem.", f: "{nome} fechou o dia com 2 aulas. Alguém chama a massagem." },
    { m: "Repetiu a dose: {nome} voltou pra segunda aula do dia sem pensar duas vezes.", f: "Repetiu a dose: {nome} voltou pra segunda aula do dia sem pensar duas vezes." },
    { m: "{nome} deu exemplo hoje — 2 aulas, 1 dia, zero desculpa.", f: "{nome} deu exemplo hoje — 2 aulas, 1 dia, zero desculpa." },
  ],
  progresso_missao: [
    { m: "O {n}º desafio já conquistado por {nome}. Ninguém para esse homem.", f: "O {n}º desafio já conquistado por {nome}. Ninguém para essa mulher." },
    { m: "{nome} fechou a missão nº {n}. A cartela tá quase inteira.", f: "{nome} fechou a missão nº {n}. A cartela tá quase inteira." },
    { m: "Mais uma pro currículo de {nome}: já são {n} missões cumpridas.", f: "Mais uma pro currículo de {nome}: já são {n} missões cumpridas." },
    { m: "{nome} tá em ritmo de campeão — {n} missões já na conta.", f: "{nome} tá em ritmo de campeã — {n} missões já na conta." },
    { m: "Missão {n} riscada da lista de {nome}. Faltam poucas.", f: "Missão {n} riscada da lista de {nome}. Faltam poucas." },
    { m: "{nome} não para: {n}ª missão cumprida essa semana.", f: "{nome} não para: {n}ª missão cumprida essa semana." },
    { m: "A cartela de {nome} já tem {n} marcadas. Quem segura essa disposição?", f: "A cartela de {nome} já tem {n} marcadas. Quem segura essa disposição?" },
    { m: "{n} missões, {nome} na cola do topo do ranking.", f: "{n} missões, {nome} na cola do topo do ranking." },
    { m: "{nome} tá devorando missão — essa foi a {n}ª.", f: "{nome} tá devorando missão — essa foi a {n}ª." },
    { m: "Passo a passo, {nome} chega lá: {n}ª missão fechada.", f: "Passo a passo, {nome} chega lá: {n}ª missão fechada." },
    { m: "{nome} deu mais um passo — {n} missões cumpridas e o resto é questão de tempo.", f: "{nome} deu mais um passo — {n} missões cumpridas e o resto é questão de tempo." },
    { m: "Contador atualizado: {nome} chegou em {n} missões.", f: "Contador atualizado: {nome} chegou em {n} missões." },
    { m: "{nome} tá construindo uma cartela e tanto — {n} já fechadas.", f: "{nome} tá construindo uma cartela e tanto — {n} já fechadas." },
    { m: "Sem pressa, mas sem pausa: {n}ª missão de {nome}.", f: "Sem pressa, mas sem pausa: {n}ª missão de {nome}." },
    { m: "{nome} vai deixando rastro de missão cumprida — já são {n}.", f: "{nome} vai deixando rastro de missão cumprida — já são {n}." },
    { m: "Dessa vez foi a missão {n}. {nome} não perde o ritmo.", f: "Dessa vez foi a missão {n}. {nome} não perde o ritmo." },
    { m: "{nome} coleciona missão que nem selo de passaporte — {n} carimbadas.", f: "{nome} coleciona missão que nem selo de passaporte — {n} carimbadas." },
    { m: "Tá difícil segurar {nome}: {n}ª missão cumprida no desafio.", f: "Tá difícil segurar {nome}: {n}ª missão cumprida no desafio." },
    { m: "{n} missões pra {nome}. O troféu já tá suando na mão.", f: "{n} missões pra {nome}. O troféu já tá suando na mão." },
  ],
  convidados: [
    { m: "{nome} já é o {n}º amigo que traz. Assim que a comunidade cresce.", f: "{nome} já é a {n}ª amiga que traz. Assim que a comunidade cresce." },
    { m: "Bike do lado nunca fica vazia perto de {nome} — {n}º convidado já.", f: "Bike do lado nunca fica vazia perto de {nome} — {n}ª convidada já." },
    { m: "{nome} tá espalhando o vício bom — {n} pessoas já trouxe pra pedalar.", f: "{nome} tá espalhando o vício bom — {n} pessoas já trouxe pra pedalar." },
    { m: "Mais um amigo na sala graças a {nome}. Já são {n}.", f: "Mais uma amiga na sala graças a {nome}. Já são {n}." },
    { m: "{nome} converte todo mundo — {n}º convidado apresentado ao pedal.", f: "{nome} converte todo mundo — {n}ª convidada apresentada ao pedal." },
    { m: "A rede de {nome} só cresce: {n} amigos já trazidos pro desafio.", f: "A rede de {nome} só cresce: {n} amigas já trazidas pro desafio." },
    { m: "Quem tem amigo assim nem precisa de propaganda — {nome} já trouxe {n}.", f: "Quem tem amiga assim nem precisa de propaganda — {nome} já trouxe {n}." },
    { m: "{nome} é a maior propaganda da Spincycle — {n}º convidado essa semana.", f: "{nome} é a maior propaganda da Spincycle — {n}ª convidada essa semana." },
    { m: "Comunidade que cresce tem gente como {nome} — {n} amigos apresentados.", f: "Comunidade que cresce tem gente como {nome} — {n} amigas apresentadas." },
    { m: "{nome} não vem sozinho — essa foi a {n}ª pessoa que trouxe junto.", f: "{nome} não vem sozinha — essa foi a {n}ª pessoa que trouxe junto." },
    { m: "Toda semana tem gente nova por causa de {nome}: já são {n}.", f: "Toda semana tem gente nova por causa de {nome}: já são {n}." },
    { m: "{nome} tá numa cruzada de espalhar bike boa — {n}º convidado no ar.", f: "{nome} tá numa cruzada de espalhar bike boa — {n}ª convidada no ar." },
    { m: "Contagiante desse jeito só {nome} — {n} amigos já entraram na roda.", f: "Contagiante desse jeito só {nome} — {n} amigas já entraram na roda." },
    { m: "{nome} traz gente boa: {n}º convidado confirmado.", f: "{nome} traz gente boa: {n}ª convidada confirmada." },
    { m: "A fila da bike do lado de {nome} nunca esfria — {n} convidados já.", f: "A fila da bike do lado de {nome} nunca esfria — {n} convidados já." },
    { m: "{nome} multiplica a comunidade — {n}ª pessoa levada pro pedal.", f: "{nome} multiplica a comunidade — {n}ª pessoa levada pro pedal." },
    { m: "Já virou hábito: {nome} chega com alguém novo. {n}º dessa vez.", f: "Já virou hábito: {nome} chega com alguém nova. {n}ª dessa vez." },
    { m: "{nome} tá com a lista cheia de gente que trouxe — {n} até agora.", f: "{nome} tá com a lista cheia de gente que trouxe — {n} até agora." },
  ],
  quase_desafio: [
    { m: "Eita, {nome} tá quase completando o desafio — {pct}% já! Vamos mandar mensagem de incentivo, minha gente.", f: "Eita, {nome} tá quase completando o desafio — {pct}% já! Vamos mandar mensagem de incentivo, minha gente." },
    { m: "Faltam só uns detalhes pra {nome} fechar tudo — já em {pct}%.", f: "Faltam só uns detalhes pra {nome} fechar tudo — já em {pct}%." },
    { m: "{nome} tá na reta final: {pct}% do desafio concluído. Segura essa torcida.", f: "{nome} tá na reta final: {pct}% do desafio concluído. Segura essa torcida." },
    { m: "Quem tá acompanhando sabe: {nome} tá pertinho, {pct}% já feito.", f: "Quem tá acompanhando sabe: {nome} tá pertinho, {pct}% já feito." },
    { m: "{pct}% pra {nome}. Falta pouco, comunidade — bora dar aquele gás.", f: "{pct}% pra {nome}. Falta pouco, comunidade — bora dar aquele gás." },
    { m: "{nome} não vai parar agora — {pct}% concluído e a reta final apertando.", f: "{nome} não vai parar agora — {pct}% concluído e a reta final apertando." },
    { m: "Com {pct}% do desafio, {nome} já pode sentir o cheiro do prêmio.", f: "Com {pct}% do desafio, {nome} já pode sentir o cheiro do prêmio." },
    { m: "Reta final: {nome} em {pct}%. Ninguém desiste nessa parte da história.", f: "Reta final: {nome} em {pct}%. Ninguém desiste nessa parte da história." },
    { m: "{nome} tá voando rumo ao fim — {pct}% já garantido.", f: "{nome} tá voando rumo ao fim — {pct}% já garantido." },
    { m: "Quase lá! {nome} já bateu {pct}% do desafio. Bora empurrar junto.", f: "Quase lá! {nome} já bateu {pct}% do desafio. Bora empurrar junto." },
    { m: "{pct}% concluído por {nome}. O resto é detalhe.", f: "{pct}% concluído por {nome}. O resto é detalhe." },
    { m: "{nome} entrou na fase decisiva: {pct}% feito, faltam os últimos passos.", f: "{nome} entrou na fase decisiva: {pct}% feito, faltam os últimos passos." },
    { m: "Comunidade, atenção: {nome} tá em {pct}%. Uma força extra ajuda agora.", f: "Comunidade, atenção: {nome} tá em {pct}%. Uma força extra ajuda agora." },
    { m: "{nome} construiu {pct}% até aqui — o final tá logo ali.", f: "{nome} construiu {pct}% até aqui — o final tá logo ali." },
    { m: "Falta pouco de verdade: {nome} já soma {pct}% do desafio.", f: "Falta pouco de verdade: {nome} já soma {pct}% do desafio." },
    { m: "{nome} não olha pra trás — {pct}% feito e o olho no prêmio.", f: "{nome} não olha pra trás — {pct}% feito e o olho no prêmio." },
    { m: "A torcida sabe: {nome} tá em {pct}%, é hora de gritar mais alto.", f: "A torcida sabe: {nome} tá em {pct}%, é hora de gritar mais alto." },
    { m: "{pct}% e contando — {nome} tá cada vez mais perto da linha de chegada.", f: "{pct}% e contando — {nome} tá cada vez mais perto da linha de chegada." },
    { m: "{nome} tá naquela fase boa do desafio: {pct}% feito, coragem redobrada.", f: "{nome} tá naquela fase boa do desafio: {pct}% feito, coragem redobrada." },
  ],
  missao_especifica: [
    { m: "{nome}, desiste não que falta pouquinho. Só um {missao}.", f: "{nome}, desiste não que falta pouquinho. Só um {missao}." },
    { m: "Falta só o {missao} pra {nome} fechar tudo. Vai que é sua hora!", f: "Falta só o {missao} pra {nome} fechar tudo. Vai que é sua hora!" },
    { m: "{nome} tá a um {missao} de completar a cartela inteira.", f: "{nome} tá a um {missao} de completar a cartela inteira." },
    { m: "Só falta o {missao}, {nome}. A gente tá na torcida por essa última!", f: "Só falta o {missao}, {nome}. A gente tá na torcida por essa última!" },
    { m: "{nome} já fez quase tudo — falta só o {missao} pra fechar com chave de ouro.", f: "{nome} já fez quase tudo — falta só o {missao} pra fechar com chave de ouro." },
    { m: "Última barreira de {nome}: o {missao}. Bora, que dá!", f: "Última barreira de {nome}: o {missao}. Bora, que dá!" },
    { m: "{nome}, essa reta final é só o {missao}. Segura firme.", f: "{nome}, essa reta final é só o {missao}. Segura firme." },
    { m: "Tão perto: falta o {missao} pra {nome} fechar o desafio inteiro.", f: "Tão perto: falta o {missao} pra {nome} fechar o desafio inteiro." },
    { m: "{nome} guardou o {missao} pro final — hora de encarar.", f: "{nome} guardou o {missao} pro final — hora de encarar." },
    { m: "Um {missao} separa {nome} da cartela cheia. Vamo que vamo!", f: "Um {missao} separa {nome} da cartela cheia. Vamo que vamo!" },
    { m: "{nome} tá cheirando o prêmio — só falta o {missao}.", f: "{nome} tá cheirando o prêmio — só falta o {missao}." },
    { m: "A comunidade sabe: {nome} só precisa do {missao} pra fechar tudo.", f: "A comunidade sabe: {nome} só precisa do {missao} pra fechar tudo." },
    { m: "{nome}, o {missao} tá esperando por você. Falta pouquinho!", f: "{nome}, o {missao} tá esperando por você. Falta pouquinho!" },
    { m: "Reta final apertada: {nome} só precisa do {missao} pra fechar tudo.", f: "Reta final apertada: {nome} só precisa do {missao} pra fechar tudo." },
    { m: "{nome} já tá com a cartela quase cheia — falta o {missao}, só isso.", f: "{nome} já tá com a cartela quase cheia — falta o {missao}, só isso." },
    { m: "Vai que é agora: {nome} a um {missao} da cartela cheia.", f: "Vai que é agora: {nome} a um {missao} da cartela cheia." },
    { m: "{nome}, não solta agora — falta só o {missao}.", f: "{nome}, não solta agora — falta só o {missao}." },
    { m: "Tudo pronto, só falta o {missao}. {nome}, essa é sua.", f: "Tudo pronto, só falta o {missao}. {nome}, essa é sua." },
    { m: "{nome} guardou o mais difícil pro fim: o {missao}. Bora encarar junto.", f: "{nome} guardou o mais difícil pro fim: o {missao}. Bora encarar junto." },
  ],
  frequencia_baixa: [
    { m: "{nome} tá vindo só no balancinho... mas de uma em uma o desafio se completa.", f: "{nome} tá vindo só no balancinho... mas de uma em uma o desafio se completa." },
    { m: "Devagar, mas sem parar: {nome} não falta com a palavra, mesmo vindo pouco.", f: "Devagar, mas sem parar: {nome} não falta com a palavra, mesmo vindo pouco." },
    { m: "{nome} vem no seu ritmo, mas vem sempre. Isso também é disciplina.", f: "{nome} vem no seu ritmo, mas vem sempre. Isso também é disciplina." },
    { m: "Não é sobre rapidez, é sobre constância — e {nome} tá mandando bem nisso.", f: "Não é sobre rapidez, é sobre constância — e {nome} tá mandando bem nisso." },
    { m: "{nome} não corre, mas também não para. Uma aula de cada vez.", f: "{nome} não corre, mas também não para. Uma aula de cada vez." },
    { m: "Ritmo tranquilo, resultado garantido: {nome} tá construindo aos poucos.", f: "Ritmo tranquilo, resultado garantido: {nome} tá construindo aos poucos." },
    { m: "{nome} prova que não precisa ser todo dia pra chegar lá.", f: "{nome} prova que não precisa ser todo dia pra chegar lá." },
    { m: "Uma aula de cada vez, {nome} vai fechando a cartela do seu jeito.", f: "Uma aula de cada vez, {nome} vai fechando a cartela do seu jeito." },
    { m: "{nome} não tem pressa, mas também não desiste. Isso conta muito.", f: "{nome} não tem pressa, mas também não desiste. Isso conta muito." },
    { m: "Sem alarde, {nome} vai fazendo a parte dele, no tempo que dá.", f: "Sem alarde, {nome} vai fazendo a parte dela, no tempo que dá." },
    { m: "{nome} lembra a gente: o importante é não parar de vez.", f: "{nome} lembra a gente: o importante é não parar de vez." },
    { m: "Vem pouco, mas vem com vontade — assim é {nome}.", f: "Vem pouco, mas vem com vontade — assim é {nome}." },
    { m: "{nome} tá no seu tempo, e isso também merece aplauso.", f: "{nome} tá no seu tempo, e isso também merece aplauso." },
    { m: "Nem todo mundo precisa ir todo dia — {nome} mostra que dá pra chegar do seu jeito.", f: "Nem todo mundo precisa ir todo dia — {nome} mostra que dá pra chegar do seu jeito." },
    { m: "{nome} não bate recorde de frequência, mas também nunca desiste.", f: "{nome} não bate recorde de frequência, mas também nunca desiste." },
    { m: "Passo curto, mas sempre pra frente — {nome} no seu ritmo.", f: "Passo curto, mas sempre pra frente — {nome} no seu ritmo." },
    { m: "{nome} ensina: o segredo é continuar, nem que seja devagar.", f: "{nome} ensina: o segredo é continuar, nem que seja devagar." },
    { m: "Nem sempre dá pra ir, mas {nome} sempre volta. Isso é o que importa.", f: "Nem sempre dá pra ir, mas {nome} sempre volta. Isso é o que importa." },
    { m: "{nome} tá escrevendo a própria história aqui, sem pressa nenhuma.", f: "{nome} tá escrevendo a própria história aqui, sem pressa nenhuma." },
  ],
};

// Escolhe uma variação de forma ESTÁVEL por evento (mesmo id sempre pega a mesma frase),
// pra não mudar de texto a cada vez que o Radar recarrega.
function hashEstavel(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) { h = (h * 31 + str.charCodeAt(i)) | 0; }
  return Math.abs(h);
}

export function escolherMsgRadar(categoria, genero, eventoId, valores = {}) {
  const lista = RADAR_MSGS[categoria];
  if (!lista || lista.length === 0 || !genero) return null;
  const idx = hashEstavel(String(eventoId)) % lista.length;
  const item = lista[idx];
  let texto = genero === "M" ? item.m : item.f;
  Object.entries(valores).forEach(([chave, val]) => {
    texto = texto.split(`{${chave}}`).join(String(val));
  });
  return texto;
}

// Decide o tier de inatividade certo a partir dos dias sem check-in.
export function categoriaInatividade(dias) {
  if (dias >= 30) return "inatividade_grave_30d";
  if (dias >= 15) return "inatividade_media_15d";
  if (dias >= 5) return "inatividade_leve_5d";
  return null;
}
